### PR TITLE
Enhancement/Update useAccountManager functionality

### PR DESCRIPTION
**Pull request by brandonlammey**
## Description
All changes relate to useAccountManager hook. 

Changes 
## Related Issue
Issue #418 

## Motivation and Context
This change adds useful callback functions for users to logout/remove all accounts in the useAccountManager hook as well as verify token status. A bug was fixed in error handling within getThumbnail functions and functionality added to maintain thumbnail images. An enhancement was added to save an originPath to be used in application routing. Function param format was modified to unify format for entire hook and callback functions. A modification was made to store accounts in order from most recent to oldest using a key array returned in accountManagerState and allows user to choose to auto set any addAccounts to active. 

## How Has This Been Tested?
Tested with Enterprise and AGO accounts within the docz environment. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by brandonlammey** [comment]
Note: JS Image() is given back in the getThumbnail functions allowing a user to store in state. This effectively caches the image. To store within localStorage/accountManagerState would add another field for org and user thumbnails to the account object (this was not done for this enhancement)

**Review by codylawson — APPROVED** [review]
Looks good, can we use async await in place of .then?

**Review by brandonlammey — COMMENTED** [review]
Updated .then() to async/await syntax

**Review by codylawson — APPROVED** [review]
Looks good

**Pull request merged**
