### PR TITLE
Bug Fix: Justify TopNav and SubNav Content right 

### PR DESCRIPTION
**Pull request by joeyHarig**
Justified right when no title is present 
Screen Shot 2020-09-11 at 3 30 56 PM

Justified Right when no TopNavList is present
Screen Shot 2020-09-11 at 3 32 55 PM

### CODE REVIEW

**Comment by codylawson** [comment]
@joeyHarig This seems to remove all padding around the title of the subnav
Screen Shot 2020-09-14 at 11 33 07 AM

**Comment by joeyHarig** [comment]
There was 0.25em of padding to the left of the subNavTitle. Now that we are using the maxScreenWidth from theme provider, the margin on either side of the subNav will be determined by the width of the screen. By removing the padding-left on title, it ensures that the title will align cleanly with the rest of the content in the app.
Screen Shot 2020-09-14 at 11 43 28 AM
Screen Shot 2020-09-14 at 11 43 19 AM

**Comment by codylawson** [comment]
@joeyHarig We'll need to add padding to every container element on the page, then. We shouldn't have titles right up against the edge of the browser.

**Comment by joeyHarig** [comment]
### Changes
- Changed screenWidth from 1440px to 1450px
- Added 1rem of padding to SubNav and TopNav content so that content never touches edges of browser
- Made SubNav a fixed height of 56px (same as AGO)

Screen Shot 2020-09-14 at 1 26 18 PM
Screen Shot 2020-09-14 at 1 26 07 PM

**Review by codylawson — APPROVED** [review]
Looks good, thanks for the updates

**Pull request merged**
