### PR TITLE
Square Loader

### PR DESCRIPTION
**Pull request by codylawson**
## Description
Add `square` prop to `Loader` for updated styles.

## Screenshots (if appropriate):
Kapture 2020-01-02 at 18 04 21

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by jgibson02** [comment]
I see that with the calcite-components version is animated between a light and a dark blue, whereas this version supports multiple colors but no color animation. Personally I think I would prefer having the animated transition between the light and dark blue, but what are your thoughts?

**Comment by macandcheese** [comment]
Thanks for making this update! We have actually been asked to remove the "square" version of this loader, and replace it with a less brand - identifiable version. 

We are working on making the changes in Calcite Components, @jochoa8 may have some more insight. Apologies for the inconvenience

**Comment by codylawson** [comment]
@macandcheese Thanks for letting us know. I'll postpone this pr until a new style is created.

**Comment by codylawson** [comment]
Closing as the loader styles will get another revamp soon.

**Pull request closed without merging**
